### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Streetwalrus** [Streetwalrus/lolibot#1]
- [ ] Rewrite Telewalrus
  - [ ] Generate API binding from Telegram docs
  - [ ] Webhooks interface with Flask
- [ ] Scraper service with PostgreSQL storage
  - [ ] Subreddits
  - [ ] Other sources
    - [ ] [headp.at](http://headp.at/)
- [ ] Inline keyboard
  - [ ] Like button
  - [ ] Next pic button
- [ ] State tracking in Redis for volatile things such as searches
- [ ] IQDB search
  - [ ] `/iqdb`
  - [ ] Sauce button in the inline keyboard
